### ISSUE TITLE
support to specify output format

### ISSUE THREAD

**Issue by aneesh-joseph** [sijpesteijn/mafia-maven-plugin#26]
the mafia plugin uses `?suite` to get the suite results, is it possible to provide an option to specify the format type like `?suite&format=xml`

**Comment by aneesh-joseph** [comment]
I'm trying to get the results parsed by the [Fitnesse Jenkins plugin](https://wiki.jenkins-ci.org/display/JENKINS/FitNesse+Plugin) but looks like the Jenkins plugin doesn't like the suite results generated  by `mafia:test`, so would like to set the format to xml as the Jenkins plugin seems to like it :smile:

**Comment by sijpesteijn** [comment]
Hi,

I would not go for the jenkins-fitnesse plugin. I was not able to get the maven plugin to work with it. What I normally use is the Publish Html Reports jenkins plugin. 
The mafia plugin will create a fitnesse_report.html in FitNesseRoot/files/mafiaResults/report/. You can use this as input for the publish html report plugin. I hope this works for you.

Cheers, Gijs
